name: Build Windows x64 (Batch Script)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup vcpkg integration
      run: vcpkg integrate install

    - name: Compile using batch file
      run: .\compile.bat
      shell: cmd

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FunnyApp-Executable
        path: "**/*.exe"
        if-no-files-found: error
